# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: fr-FR

# Site title
title: "Capsule 2024"

# A description of your site for meta tag, search engine results.
description: "Capsule 2024 le blog de voyage du tour du monde en 4x4 de Laurence & Emmanuel Rudloff"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://scriptor-jekyll.netlify.com"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Liste des catégories
collections:
  category:
    output: true # générer la page HTML
    permalink: /:collection/:name/index.html
    # exemple -> /category/informatique/index.html

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
      # layout utilisé -> _layouts/category.html


# Site navigation - each item must have a title and a url.
navigation:
  - text: Construction
    url: /category/construction/
  - text: Voyage
    url: /
  - text: A propos
    url: /about/
  - text: Tracé
    url: /trace/
  - text: Tags
    url: /tags/
  #- text: Download
  #  url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# The shortname for your Disqus site to enable comments.
disqus: capsule2024

# Colors
accent_color: '#262626'

# Site footer
footer:
  content: "&copy; Capsule2024 all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Keywords
keywords:
  - Blog
  - Voyage
  - RoadTrip
  - Pays
  - Découverte
  - Discovery
  - Road
  - Route